# Generated by Django 5.0 on 2023-12-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0022_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('numero_de_telefono', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=260)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
    ]
